Industria.ST = {};
Industria.files = {};
---"Industria.controllers" contains all the saved Units references, ownership and properties.
---The nodes aren't handled in this section but in "Industria.units"
---
---The functions present in this table are used to create units, remove or serialize them.
Industria.controllers = {
    ---Contiene gli id delle unità di un giocatore nel formato:
    ---{nome_owner={codice1, codice2, codice3}}
    ---@type table<owner, unit_id[]>
    ids = {},
    ---Contiene le unità con il codice associato nel formato:
    ---{codice1={...},codice2={...}}
    ---@type table<unit_code,Unit>
    units = {}
};
---Contiene le unità di IO con il codice associato, nel formato:
---{codice1={...},codice2={...}}
---@type table<io_unit_code,IOUnit>
Industria.iounits = {}

---"Industria.runtime" contains all the interpreters of all the units defined
---in "Industria.controllers" that are enabled and it's used to execute the code.
---
---All the errors generated by the unit execution or code errors (syntax) are saved here.
---
---This section is not serialized to disk, it's filled when the world is loaded or when
---new units are created or removed.
Industria.runtime = {
    ---Unità corrente: il ciclo di esecuzione esegue un'unità alla volta: imposta questa
    ---variabile all'unità che è in esecuzione 
    current_unit = nil,
    ---Contiene tutte le unità caricate/create: se un unità non è
    ---presente in questa tabella allora non può essere avviata a runtime
    ---
    ---@type table<unit_code,RTInfo> Tabella che associa unit_code a {enabled,interpreter}
    units = {},
};
