Industria.ST = {};
Industria.files = {};
---"Industria.controllers" contains all the saved Units references, ownership and properties.
---The nodes aren't handled in this section but in "Industria.units"
---
---The functions present in this table are used to create units, remove or serialize them.
Industria.controllers = {
    ---Contiene gli id delle unità di un giocatore nel formato:
    ---{nome_owner={codice1, codice2, codice3}}
    ---@type table<owner, ControllerCODE[]>
    player_controllers = {},
    ---Contiene le unità con il codice associato nel formato:
    ---{codice1={...},codice2={...}}
    ---@type table<ControllerCODE,Controller>
    registered_controllers = {}
};

---Contains all the contents and functions related to the IO units registered in the world:
---this doesn't assure that the IOUnit is bounded to a unit or an enabled unit.
Industria.iounits = {
    ---Contiene gli id delle unità di un giocatore nel formato:
    ---{nome_owner={codice1, codice2, codice3}}
    ids = {},
    ---Contiene le unità di IO con il codice associato, nel formato:
    ---{codice1={...},codice2={...}}
    ---@type table<IOUnitCODE,IOUnit>
    registered = {}
}

---"Industria.runtime" contains all the interpreters of all the units defined
---in "Industria.controllers" that are enabled and it's used to execute the code.
---
---All the errors generated by the unit execution or code errors (syntax) are saved here.
---
---This section is not serialized to disk, it's filled when the world is loaded or when
---new units are created or removed.
Industria.runtime = {
    ---Unità corrente: il ciclo di esecuzione esegue un'unità alla volta: imposta questa
    ---variabile all'unità che è in esecuzione
    current_unit = nil,
    ---Contiene tutte le unità caricate/create: se un unità non è
    ---presente in questa tabella allora non può essere avviata a runtime
    ---
    ---@type table<ControllerCODE,RTInfo> Tabella che associa unit_code a {enabled,interpreter}
    runtime_units = {},
    ---Contiene tutta la gestione per il runtime delle IOUnits
    ---
    iounits = {}
};


dofile(Industria.path .. "/core/STCore.lua");
dofile(Industria.path .. "/core/STFiles.lua");
dofile(Industria.path .. "/core/controllers.lua");
dofile(Industria.path .. "/core/iounits.lua");
dofile(Industria.path .. "/core/runtime.lua");
dofile(Industria.path .. "/core/ioruntime.lua");